AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Glue Job, Crawlers, S3 Bucket Creation, and Athena Querying
Resources:
  DataBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: "sample-ws-mac-192-bucket"
  GlueJob1:
    Type: 'AWS::Glue::Job'
    Properties:
      Role: !Ref GlueRole
      Command:
        Name: 'glueetl'
        ScriptLocation: !Sub 's3://${DataBucket}/scripts/job1/script.py'
      DefaultArguments:
        "--TempDir": !Sub 's3://${DataBucket}/temp-dir/'
        "--enable-notebook": "true"
        "--notebook-dir": !Sub 's3://${DataBucket}/notebooks/'
        "--source_crawler": !Ref SourceCrawler
        "--target_crawler": !Ref TargetCrawler
        --SOURCE_CRAWLER: sample-ws-mac-23SourceCrawler
        --JOB_NAME: job1
      GlueVersion: '2.0'
      MaxRetries: 3
      Name: "sample-ws-mac-192GlueJob1"
      ExecutionProperty:
        MaxConcurrentRuns: 1
  GlueJob2:
    Type: 'AWS::Glue::Job'
    Properties:
      Role: !Ref GlueRole
      Command:
        Name: 'glueetl'
        ScriptLocation: !Sub 's3://${DataBucket}/scripts/job2/script.py'
      DefaultArguments:
        "--TempDir": !Sub 's3://${DataBucket}/temp-dir/'
        "--enable-notebook": "true"
        "--notebook-dir": !Sub 's3://${DataBucket}/notebooks/'
        "--source_crawler": !Ref SourceCrawler
        "--target_crawler": !Ref TargetCrawler
        --JOB_NAME: "job2"
        --SOURCE_CRAWLER: sample-ws-mac-23SourceCrawler
      GlueVersion: '2.0'
      MaxRetries: 3
      Name: "sample-ws-mac-192GlueJob2"
      ExecutionProperty:
        MaxConcurrentRuns: 1
  SourceCrawler:
    Type: 'AWS::Glue::Crawler'
    Properties:
      Role: !Ref GlueRole
      DatabaseName: 'sample-ws-mac-192sourcedatabase'
      Schedule:
        ScheduleExpression: 'cron(0 12 * * ? *)'
      Targets:
        S3Targets:
          - Path: !Sub 's3://${DataBucket}/source'
      Name: "sample-ws-mac-192SourceCrawler"
  TargetCrawler:
    Type: 'AWS::Glue::Crawler'
    Properties:
      Role: !Ref GlueRole
      DatabaseName: 'sample-ws-mac-192targetdatabase'
      Schedule:
        ScheduleExpression: 'cron(0 12 * * ? *)'
      Targets:
        S3Targets:
          - Path: !Sub 's3://${DataBucket}/landing'
      Name: "sample-ws-mac-192TargetCrawler"
  sourcedatabase:
    Type: 'AWS::Glue::Database'
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: "sample-ws-mac-192sourcedatabase"
        Description: 'sample-ws-mac-192 Source Catalog'
  targetdatabase:
    Type: 'AWS::Glue::Database'
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: "sample-ws-mac-192targetdatabase"
        Description: 'sample-ws-mac-192 Target Catalog'
  GlueRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'glue.amazonaws.com'
            Action: 'sts:AssumeRole'
      Path: '/'
      Policies:
        - PolicyName: "sample-ws-mac-192GluePolicy"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 's3:*'
                  - 'glue:*'
                Resource: '*'
