AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Glue Job, Crawlers, S3 Bucket Creation, and Athena Querying
Resources:
  DataBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: "glue-jupyter-ws-3-bucket"
  GlueJob1:
    Type: 'AWS::Glue::Job'
    Properties:
      Role: !Ref GlueRole
      Command:
        Name: 'glueetl'
        ScriptLocation: !Sub 's3://${DataBucket}/scripts/job1/script.py'
      DefaultArguments:
        "--TempDir": !Sub 's3://${DataBucket}/temp-dir/'
        "--enable-notebook": "true"
        "--notebook-dir": !Sub 's3://${DataBucket}/notebooks/'
        --JOB_NAME: job1
        --SOURCE_CRAWLER: glue-jupyter-ws-3SourceCrawler
        --BUCKET_NAME: glue-jupyter-ws-3-bucket
        --additional-python-modules: s3://glue-jupyter-ws-3-bucket/lib/utils-0.1-py3-none-any.whl
      GlueVersion: '2.0'
      MaxRetries: 3
      Name: "glue-jupyter-ws-3GlueJob1"
      ExecutionProperty:
        MaxConcurrentRuns: 1
  GlueJob2:
    Type: 'AWS::Glue::Job'
    Properties:
      Role: !Ref GlueRole
      Command:
        Name: 'glueetl'
        ScriptLocation: !Sub 's3://${DataBucket}/scripts/job2/script.py'
      DefaultArguments:
        "--TempDir": !Sub 's3://${DataBucket}/temp-dir/'
        "--enable-notebook": "true"
        "--notebook-dir": !Sub 's3://${DataBucket}/notebooks/'
        --JOB_NAME: "job2"
        --SOURCE_CRAWLER: glue-jupyter-ws-3SourceCrawler
        --BUCKET_NAME: glue-jupyter-ws-3-bucket
        --additional-python-modules: s3://glue-jupyter-ws-3-bucket/lib/utils-0.1-py3-none-any.whl
      GlueVersion: '2.0'
      MaxRetries: 3
      Name: "glue-jupyter-ws-3GlueJob2"
      ExecutionProperty:
        MaxConcurrentRuns: 1
  SourceCrawler:
    Type: 'AWS::Glue::Crawler'
    Properties:
      Role: !Ref GlueRole
      DatabaseName: 'glue-jupyter-ws-3sourcedatabase'
      Schedule:
        ScheduleExpression: 'cron(0 12 * * ? *)'
      Targets:
        S3Targets:
          - Path: !Sub 's3://${DataBucket}/source'
      Name: "glue-jupyter-ws-3SourceCrawler"
  TargetCrawler:
    Type: 'AWS::Glue::Crawler'
    Properties:
      Role: !Ref GlueRole
      DatabaseName: 'glue-jupyter-ws-3targetdatabase'
      Schedule:
        ScheduleExpression: 'cron(0 12 * * ? *)'
      Targets:
        S3Targets:
          - Path: !Sub 's3://${DataBucket}/landing'
      Name: "glue-jupyter-ws-3TargetCrawler"
  sourcedatabase:
    Type: 'AWS::Glue::Database'
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: "glue-jupyter-ws-3sourcedatabase"
        Description: 'glue-jupyter-ws-3 Source Catalog'
  targetdatabase:
    Type: 'AWS::Glue::Database'
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: "glue-jupyter-ws-3targetdatabase"
        Description: 'glue-jupyter-ws-3 Target Catalog'
  GlueRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'glue.amazonaws.com'
            Action: 'sts:AssumeRole'
      Path: '/'
      Policies:
        - PolicyName: "glue-jupyter-ws-3GluePolicy"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 's3:*'
                  - 'glue:*'
                Resource: '*'
